champions = [
    {
        key: '266',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Aatrox.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg',
        name: 'Aatrox',
        title: 'the Darkin Blade',
        stats: {
            hp: 580,
            mp: 0,
            attackdamage: 60,
            attackspeed: 0.651,
            attackrange: 175,
        },
    },
    {
        key: '103',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ahri.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg',
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        stats: {
            hp: 526,
            mp: 418,
            attackdamage: 53.04,
            attackspeed: 0.668,
            attackrange: 550,
        },
    },
    {
        key: '84',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Akali.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg',
        name: 'Akali',
        title: 'the Rogue Assassin',
        stats: {
            hp: 575,
            mp: 200,
            attackdamage: 62.4,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '12',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Alistar.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_0.jpg',
        name: 'Alistar',
        title: 'the Minotaur',
        stats: {
            hp: 600,
            mp: 350,
            attackdamage: 62,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '32',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Amumu.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg',
        name: 'Amumu',
        title: 'the Sad Mummy',
        stats: {
            hp: 615,
            mp: 285,
            attackdamage: 53.38,
            attackspeed: 0.736,
            attackrange: 125,
        },
    },
    {
        key: '34',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Anivia.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg',
        name: 'Anivia',
        title: 'the Cryophoenix',
        stats: {
            hp: 480,
            mp: 495,
            attackdamage: 51.376,
            attackspeed: 0.625,
            attackrange: 600,
        },
    },
    {
        key: '1',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Annie.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg',
        name: 'Annie',
        title: 'the Dark Child',
        stats: {
            hp: 524,
            mp: 418,
            attackdamage: 50.41,
            attackspeed: 0.579,
            attackrange: 625,
        },
    },
    {
        key: '523',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Aphelios.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg',
        name: 'Aphelios',
        title: 'the Weapon of the Faithful',
        stats: {
            hp: 530,
            mp: 348,
            attackdamage: 57,
            attackspeed: 0.64,
            attackrange: 550,
        },
    },
    {
        key: '22',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ashe.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg',
        name: 'Ashe',
        title: 'the Frost Archer',
        stats: {
            hp: 570,
            mp: 280,
            attackdamage: 59,
            attackspeed: 0.658,
            attackrange: 600,
        },
    },
    {
        key: '136',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/AurelionSol.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg',
        name: 'Aurelion Sol',
        title: 'The Star Forger',
        stats: {
            hp: 575,
            mp: 350,
            attackdamage: 57,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '268',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Azir.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg',
        name: 'Azir',
        title: 'the Emperor of the Sands',
        stats: {
            hp: 552,
            mp: 480,
            attackdamage: 52,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '432',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Bard.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg',
        name: 'Bard',
        title: 'the Wandering Caretaker',
        stats: {
            hp: 560,
            mp: 350,
            attackdamage: 52,
            attackspeed: 0.625,
            attackrange: 500,
        },
    },
    {
        key: '53',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Blitzcrank.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        stats: {
            hp: 582.6,
            mp: 267.2,
            attackdamage: 61.54,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '63',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Brand.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Brand_0.jpg',
        name: 'Brand',
        title: 'the Burning Vengeance',
        stats: {
            hp: 519.68,
            mp: 469,
            attackdamage: 57.04,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '201',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Braum.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg',
        name: 'Braum',
        title: 'the Heart of the Freljord',
        stats: {
            hp: 540,
            mp: 310.6,
            attackdamage: 55.376,
            attackspeed: 0.644,
            attackrange: 125,
        },
    },
    {
        key: '51',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Caitlyn.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg',
        name: 'Caitlyn',
        title: 'the Sheriff of Piltover',
        stats: {
            hp: 510,
            mp: 313.7,
            attackdamage: 62,
            attackspeed: 0.681,
            attackrange: 650,
        },
    },
    {
        key: '164',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Camille.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Camille_0.jpg',
        name: 'Camille',
        title: 'the Steel Shadow',
        stats: {
            hp: 575.6,
            mp: 338.8,
            attackdamage: 68,
            attackspeed: 0.644,
            attackrange: 125,
        },
    },
    {
        key: '69',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Cassiopeia.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Cassiopeia_0.jpg',
        name: 'Cassiopeia',
        title: "the Serpent's Embrace",
        stats: {
            hp: 560,
            mp: 350,
            attackdamage: 53,
            attackspeed: 0.647,
            attackrange: 550,
        },
    },
    {
        key: '42',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Corki.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Corki_0.jpg',
        name: 'Corki',
        title: 'the Daring Bombardier',
        stats: {
            hp: 518,
            mp: 350,
            attackdamage: 55,
            attackspeed: 0.638,
            attackrange: 550,
        },
    },
    {
        key: '122',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Darius.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg',
        name: 'Darius',
        title: 'the Hand of Noxus',
        stats: {
            hp: 582.24,
            mp: 263,
            attackdamage: 64,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '131',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Diana.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg',
        name: 'Diana',
        title: 'Scorn of the Moon',
        stats: {
            hp: 570,
            mp: 375,
            attackdamage: 57,
            attackspeed: 0.625,
            attackrange: 150,
        },
    },
    {
        key: '119',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Draven.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg',
        name: 'Draven',
        title: 'the Glorious Executioner',
        stats: {
            hp: 605,
            mp: 360.56,
            attackdamage: 60,
            attackspeed: 0.679,
            attackrange: 550,
        },
    },
    {
        key: '245',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ekko.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg',
        name: 'Ekko',
        title: 'the Boy Who Shattered Time',
        stats: {
            hp: 585,
            mp: 280,
            attackdamage: 58,
            attackspeed: 0.688,
            attackrange: 125,
        },
    },
    {
        key: '60',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Elise.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg',
        name: 'Elise',
        title: 'the Spider Queen',
        stats: {
            hp: 534,
            mp: 324,
            attackdamage: 55,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '28',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Evelynn.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Evelynn_0.jpg',
        name: 'Evelynn',
        title: "Agony's Embrace",
        stats: {
            hp: 572,
            mp: 315,
            attackdamage: 61,
            attackspeed: 0.667,
            attackrange: 125,
        },
    },
    {
        key: '81',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ezreal.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg',
        name: 'Ezreal',
        title: 'the Prodigal Explorer',
        stats: {
            hp: 530,
            mp: 375,
            attackdamage: 60,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '9',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Fiddlesticks.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg',
        name: 'Fiddlesticks',
        title: 'the Ancient Fear',
        stats: {
            hp: 580.4,
            mp: 500,
            attackdamage: 55.36,
            attackspeed: 0.625,
            attackrange: 480,
        },
    },
    {
        key: '114',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Fiora.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg',
        name: 'Fiora',
        title: 'the Grand Duelist',
        stats: {
            hp: 550,
            mp: 300,
            attackdamage: 68,
            attackspeed: 0.69,
            attackrange: 150,
        },
    },
    {
        key: '105',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Fizz.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fizz_0.jpg',
        name: 'Fizz',
        title: 'the Tidal Trickster',
        stats: {
            hp: 570,
            mp: 317.2,
            attackdamage: 58.04,
            attackspeed: 0.658,
            attackrange: 175,
        },
    },
    {
        key: '3',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Galio.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Galio_0.jpg',
        name: 'Galio',
        title: 'the Colossus',
        stats: {
            hp: 562,
            mp: 500,
            attackdamage: 59,
            attackspeed: 0.625,
            attackrange: 150,
        },
    },
    {
        key: '41',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gangplank.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg',
        name: 'Gangplank',
        title: 'the Saltwater Scourge',
        stats: {
            hp: 540,
            mp: 280,
            attackdamage: 64,
            attackspeed: 0.658,
            attackrange: 125,
        },
    },
    {
        key: '86',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Garen.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg',
        name: 'Garen',
        title: 'The Might of Demacia',
        stats: {
            hp: 620,
            mp: 0,
            attackdamage: 66,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '150',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gnar.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gnar_0.jpg',
        name: 'Gnar',
        title: 'the Missing Link',
        stats: {
            hp: 510,
            mp: 100,
            attackdamage: 59,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '79',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gragas.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gragas_0.jpg',
        name: 'Gragas',
        title: 'the Rabble Rouser',
        stats: {
            hp: 600,
            mp: 400,
            attackdamage: 64,
            attackspeed: 0.675,
            attackrange: 125,
        },
    },
    {
        key: '104',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Graves.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg',
        name: 'Graves',
        title: 'the Outlaw',
        stats: {
            hp: 555,
            mp: 325,
            attackdamage: 68,
            attackspeed: 0.475,
            attackrange: 425,
        },
    },
    {
        key: '120',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Hecarim.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hecarim_0.jpg',
        name: 'Hecarim',
        title: 'the Shadow of War',
        stats: {
            hp: 580,
            mp: 277.2,
            attackdamage: 66,
            attackspeed: 0.67,
            attackrange: 175,
        },
    },
    {
        key: '74',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Heimerdinger.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg',
        name: 'Heimerdinger',
        title: 'the Revered Inventor',
        stats: {
            hp: 488,
            mp: 385,
            attackdamage: 55.536,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '420',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Illaoi.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Illaoi_0.jpg',
        name: 'Illaoi',
        title: 'the Kraken Priestess',
        stats: {
            hp: 585.6,
            mp: 300,
            attackdamage: 68,
            attackspeed: 0.571,
            attackrange: 125,
        },
    },
    {
        key: '39',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Irelia.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg',
        name: 'Irelia',
        title: 'the Blade Dancer',
        stats: {
            hp: 580,
            mp: 350,
            attackdamage: 63,
            attackspeed: 0.656,
            attackrange: 200,
        },
    },
    {
        key: '427',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ivern.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ivern_0.jpg',
        name: 'Ivern',
        title: 'the Green Father',
        stats: {
            hp: 585,
            mp: 450,
            attackdamage: 50,
            attackspeed: 0.644,
            attackrange: 475,
        },
    },
    {
        key: '40',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Janna.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Janna_0.jpg',
        name: 'Janna',
        title: "the Storm's Fury",
        stats: {
            hp: 500,
            mp: 350,
            attackdamage: 46,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '59',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/JarvanIV.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg',
        name: 'Jarvan IV',
        title: 'the Exemplar of Demacia',
        stats: {
            hp: 570,
            mp: 300,
            attackdamage: 64,
            attackspeed: 0.658,
            attackrange: 175,
        },
    },
    {
        key: '24',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jax.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_0.jpg',
        name: 'Jax',
        title: 'Grandmaster at Arms',
        stats: {
            hp: 592.8,
            mp: 338.8,
            attackdamage: 68,
            attackspeed: 0.638,
            attackrange: 125,
        },
    },
    {
        key: '126',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jayce.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg',
        name: 'Jayce',
        title: 'the Defender of Tomorrow',
        stats: {
            hp: 560,
            mp: 375,
            attackdamage: 54,
            attackspeed: 0.658,
            attackrange: 125,
        },
    },
    {
        key: '202',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jhin.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jhin_0.jpg',
        name: 'Jhin',
        title: 'the Virtuoso',
        stats: {
            hp: 585,
            mp: 300,
            attackdamage: 59,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '222',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jinx.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg',
        name: 'Jinx',
        title: 'the Loose Cannon',
        stats: {
            hp: 610,
            mp: 245,
            attackdamage: 57,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '429',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kalista.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kalista_0.jpg',
        name: 'Kalista',
        title: 'the Spear of Vengeance',
        stats: {
            hp: 534,
            mp: 250,
            attackdamage: 69,
            attackspeed: 0.694,
            attackrange: 525,
        },
    },
    {
        key: '43',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Karma.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karma_0.jpg',
        name: 'Karma',
        title: 'the Enlightened One',
        stats: {
            hp: 534,
            mp: 374,
            attackdamage: 53.544,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '30',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Karthus.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karthus_0.jpg',
        name: 'Karthus',
        title: 'the Deathsinger',
        stats: {
            hp: 550,
            mp: 467,
            attackdamage: 45.66,
            attackspeed: 0.625,
            attackrange: 450,
        },
    },
    {
        key: '38',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kassadin.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kassadin_0.jpg',
        name: 'Kassadin',
        title: 'the Void Walker',
        stats: {
            hp: 576,
            mp: 400,
            attackdamage: 58.852,
            attackspeed: 0.64,
            attackrange: 150,
        },
    },
    {
        key: '55',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Katarina.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg',
        name: 'Katarina',
        title: 'the Sinister Blade',
        stats: {
            hp: 602,
            mp: 0,
            attackdamage: 58,
            attackspeed: 0.658,
            attackrange: 125,
        },
    },
    {
        key: '10',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kayle.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg',
        name: 'Kayle',
        title: 'the Righteous',
        stats: {
            hp: 600,
            mp: 330,
            attackdamage: 50,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '141',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kayn.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayn_0.jpg',
        name: 'Kayn',
        title: 'the Shadow Reaper',
        stats: {
            hp: 585,
            mp: 410,
            attackdamage: 68,
            attackspeed: 0.669,
            attackrange: 175,
        },
    },
    {
        key: '85',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kennen.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg',
        name: 'Kennen',
        title: 'the Heart of the Tempest',
        stats: {
            hp: 541,
            mp: 200,
            attackdamage: 48,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '203',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kindred.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_0.jpg',
        name: 'Kindred',
        title: 'The Eternal Hunters',
        stats: {
            hp: 540,
            mp: 300,
            attackdamage: 65,
            attackspeed: 0.625,
            attackrange: 500,
        },
    },
    {
        key: '240',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kled.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kled_0.jpg',
        name: 'Kled',
        title: 'the Cantankerous Cavalier',
        stats: {
            hp: 340,
            mp: 100,
            attackdamage: 65,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '96',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/KogMaw.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/KogMaw_0.jpg',
        name: "Kog'Maw",
        title: 'the Mouth of the Abyss',
        stats: {
            hp: 565,
            mp: 325,
            attackdamage: 61,
            attackspeed: 0.665,
            attackrange: 500,
        },
    },
    {
        key: '64',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/LeeSin.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg',
        name: 'Lee Sin',
        title: 'the Blind Monk',
        stats: {
            hp: 575,
            mp: 200,
            attackdamage: 70,
            attackspeed: 0.651,
            attackrange: 125,
        },
    },
    {
        key: '89',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Leona.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg',
        name: 'Leona',
        title: 'the Radiant Dawn',
        stats: {
            hp: 576.16,
            mp: 302.2,
            attackdamage: 60.04,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '876',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lillia.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lillia_0.jpg',
        name: 'Lillia',
        title: 'the Bashful Bloom',
        stats: {
            hp: 580,
            mp: 410,
            attackdamage: 61,
            attackspeed: 0.625,
            attackrange: 325,
        },
    },
    {
        key: '127',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lissandra.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg',
        name: 'Lissandra',
        title: 'the Ice Witch',
        stats: {
            hp: 550,
            mp: 475,
            attackdamage: 53,
            attackspeed: 0.656,
            attackrange: 550,
        },
    },
    {
        key: '236',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lucian.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg',
        name: 'Lucian',
        title: 'the Purifier',
        stats: {
            hp: 571,
            mp: 348.88,
            attackdamage: 64,
            attackspeed: 0.638,
            attackrange: 500,
        },
    },
    {
        key: '117',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lulu.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg',
        name: 'Lulu',
        title: 'the Fae Sorceress',
        stats: {
            hp: 525,
            mp: 350,
            attackdamage: 47,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '99',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lux.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg',
        name: 'Lux',
        title: 'the Lady of Luminosity',
        stats: {
            hp: 490,
            mp: 480,
            attackdamage: 53.54,
            attackspeed: 0.669,
            attackrange: 550,
        },
    },
    {
        key: '54',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Malphite.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg',
        name: 'Malphite',
        title: 'Shard of the Monolith',
        stats: {
            hp: 575,
            mp: 280,
            attackdamage: 61.97,
            attackspeed: 0.736,
            attackrange: 125,
        },
    },
    {
        key: '90',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Malzahar.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malzahar_0.jpg',
        name: 'Malzahar',
        title: 'the Prophet of the Void',
        stats: {
            hp: 537,
            mp: 375,
            attackdamage: 55,
            attackspeed: 0.625,
            attackrange: 500,
        },
    },
    {
        key: '57',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Maokai.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Maokai_0.jpg',
        name: 'Maokai',
        title: 'the Twisted Treant',
        stats: {
            hp: 565,
            mp: 375,
            attackdamage: 63.54,
            attackspeed: 0.8,
            attackrange: 125,
        },
    },
    {
        key: '11',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MasterYi.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg',
        name: 'Master Yi',
        title: 'the Wuju Bladesman',
        stats: {
            hp: 598.56,
            mp: 250.56,
            attackdamage: 66,
            attackspeed: 0.679,
            attackrange: 125,
        },
    },
    {
        key: '21',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MissFortune.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg',
        name: 'Miss Fortune',
        title: 'the Bounty Hunter',
        stats: {
            hp: 570,
            mp: 325.84,
            attackdamage: 52,
            attackspeed: 0.656,
            attackrange: 550,
        },
    },
    {
        key: '82',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Mordekaiser.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg',
        name: 'Mordekaiser',
        title: 'the Iron Revenant',
        stats: {
            hp: 575,
            mp: 100,
            attackdamage: 61,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '25',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Morgana.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg',
        name: 'Morgana',
        title: 'the Fallen',
        stats: {
            hp: 560,
            mp: 340,
            attackdamage: 56,
            attackspeed: 0.625,
            attackrange: 450,
        },
    },
    {
        key: '267',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nami.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg',
        name: 'Nami',
        title: 'the Tidecaller',
        stats: {
            hp: 475,
            mp: 365,
            attackdamage: 51.208,
            attackspeed: 0.644,
            attackrange: 550,
        },
    },
    {
        key: '75',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nasus.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg',
        name: 'Nasus',
        title: 'the Curator of the Sands',
        stats: {
            hp: 561.2,
            mp: 325.6,
            attackdamage: 67,
            attackspeed: 0.638,
            attackrange: 125,
        },
    },
    {
        key: '111',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nautilus.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_0.jpg',
        name: 'Nautilus',
        title: 'the Titan of the Depths',
        stats: {
            hp: 576.48,
            mp: 400,
            attackdamage: 61,
            attackspeed: 0.706,
            attackrange: 175,
        },
    },
    {
        key: '518',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Neeko.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Neeko_0.jpg',
        name: 'Neeko',
        title: 'the Curious Chameleon',
        stats: {
            hp: 540,
            mp: 450,
            attackdamage: 48,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '76',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nidalee.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nidalee_0.jpg',
        name: 'Nidalee',
        title: 'the Bestial Huntress',
        stats: {
            hp: 545,
            mp: 295,
            attackdamage: 58,
            attackspeed: 0.638,
            attackrange: 525,
        },
    },
    {
        key: '56',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nocturne.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg',
        name: 'Nocturne',
        title: 'the Eternal Nightmare',
        stats: {
            hp: 585,
            mp: 275,
            attackdamage: 62,
            attackspeed: 0.721,
            attackrange: 125,
        },
    },
    {
        key: '2',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Olaf.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Olaf_0.jpg',
        name: 'Olaf',
        title: 'the Berserker',
        stats: {
            hp: 597.24,
            mp: 315.6,
            attackdamage: 68,
            attackspeed: 0.694,
            attackrange: 125,
        },
    },
    {
        key: '61',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Orianna.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg',
        name: 'Orianna',
        title: 'the Lady of Clockwork',
        stats: {
            hp: 530,
            mp: 418,
            attackdamage: 40.368,
            attackspeed: 0.658,
            attackrange: 525,
        },
    },
    {
        key: '516',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ornn.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg',
        name: 'Ornn',
        title: 'The Fire below the Mountain',
        stats: {
            hp: 590,
            mp: 340.6,
            attackdamage: 69,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '80',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Pantheon.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg',
        name: 'Pantheon',
        title: 'the Unbreakable Spear',
        stats: {
            hp: 580,
            mp: 317.12,
            attackdamage: 64,
            attackspeed: 0.644,
            attackrange: 175,
        },
    },
    {
        key: '78',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Poppy.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_0.jpg',
        name: 'Poppy',
        title: 'Keeper of the Hammer',
        stats: {
            hp: 540,
            mp: 280,
            attackdamage: 64,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '555',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Pyke.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg',
        name: 'Pyke',
        title: 'the Bloodharbor Ripper',
        stats: {
            hp: 600,
            mp: 415,
            attackdamage: 62,
            attackspeed: 0.667,
            attackrange: 150,
        },
    },
    {
        key: '246',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Qiyana.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Qiyana_0.jpg',
        name: 'Qiyana',
        title: 'Empress of the Elements',
        stats: {
            hp: 590,
            mp: 320,
            attackdamage: 64,
            attackspeed: 0.625,
            attackrange: 150,
        },
    },
    {
        key: '133',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Quinn.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Quinn_0.jpg',
        name: 'Quinn',
        title: "Demacia's Wings",
        stats: {
            hp: 532.8,
            mp: 268.8,
            attackdamage: 59,
            attackspeed: 0.668,
            attackrange: 525,
        },
    },
    {
        key: '497',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rakan.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rakan_0.jpg',
        name: 'Rakan',
        title: 'The Charmer',
        stats: {
            hp: 540,
            mp: 315,
            attackdamage: 62,
            attackspeed: 0.635,
            attackrange: 300,
        },
    },
    {
        key: '33',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rammus.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg',
        name: 'Rammus',
        title: 'the Armordillo',
        stats: {
            hp: 564.48,
            mp: 310.44,
            attackdamage: 55.88,
            attackspeed: 0.656,
            attackrange: 125,
        },
    },
    {
        key: '421',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/RekSai.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/RekSai_0.jpg',
        name: "Rek'Sai",
        title: 'the Void Burrower',
        stats: {
            hp: 570,
            mp: 100,
            attackdamage: 64,
            attackspeed: 0.667,
            attackrange: 175,
        },
    },
    {
        key: '58',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Renekton.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg',
        name: 'Renekton',
        title: 'the Butcher of the Sands',
        stats: {
            hp: 575,
            mp: 100,
            attackdamage: 69,
            attackspeed: 0.665,
            attackrange: 125,
        },
    },
    {
        key: '107',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rengar.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rengar_0.jpg',
        name: 'Rengar',
        title: 'the Pridestalker',
        stats: {
            hp: 585,
            mp: 4,
            attackdamage: 68,
            attackspeed: 0.667,
            attackrange: 125,
        },
    },
    {
        key: '92',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Riven.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Riven_0.jpg',
        name: 'Riven',
        title: 'the Exile',
        stats: {
            hp: 560,
            mp: 0,
            attackdamage: 64,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '68',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rumble.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rumble_0.jpg',
        name: 'Rumble',
        title: 'the Mechanized Menace',
        stats: {
            hp: 589,
            mp: 100,
            attackdamage: 61,
            attackspeed: 0.644,
            attackrange: 125,
        },
    },
    {
        key: '13',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ryze.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ryze_0.jpg',
        name: 'Ryze',
        title: 'the Rune Mage',
        stats: {
            hp: 575,
            mp: 300,
            attackdamage: 58,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '360',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Samira.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_0.jpg',
        name: 'Samira',
        title: 'the Desert Rose',
        stats: {
            hp: 530,
            mp: 348.88,
            attackdamage: 57,
            attackspeed: 0.658,
            attackrange: 500,
        },
    },
    {
        key: '113',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sejuani.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg',
        name: 'Sejuani',
        title: 'Fury of the North',
        stats: {
            hp: 560,
            mp: 400,
            attackdamage: 66,
            attackspeed: 0.688,
            attackrange: 150,
        },
    },
    {
        key: '235',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Senna.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg',
        name: 'Senna',
        title: 'the Redeemer',
        stats: {
            hp: 520,
            mp: 350,
            attackdamage: 50,
            attackspeed: 0.625,
            attackrange: 600,
        },
    },
    {
        key: '147',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Seraphine.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Seraphine_0.jpg',
        name: 'Seraphine',
        title: 'the Starry-Eyed Songstress',
        stats: {
            hp: 500,
            mp: 440,
            attackdamage: 55,
            attackspeed: 0.669,
            attackrange: 525,
        },
    },
    {
        key: '875',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sett.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg',
        name: 'Sett',
        title: 'the Boss',
        stats: {
            hp: 600,
            mp: 0,
            attackdamage: 60,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '35',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shaco.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_0.jpg',
        name: 'Shaco',
        title: 'the Demon Jester',
        stats: {
            hp: 587,
            mp: 297.2,
            attackdamage: 63,
            attackspeed: 0.694,
            attackrange: 125,
        },
    },
    {
        key: '98',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shen.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg',
        name: 'Shen',
        title: 'the Eye of Twilight',
        stats: {
            hp: 540,
            mp: 400,
            attackdamage: 60,
            attackspeed: 0.751,
            attackrange: 125,
        },
    },
    {
        key: '102',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shyvana.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shyvana_0.jpg',
        name: 'Shyvana',
        title: 'the Half-Dragon',
        stats: {
            hp: 595,
            mp: 100,
            attackdamage: 66,
            attackspeed: 0.658,
            attackrange: 125,
        },
    },
    {
        key: '27',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Singed.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg',
        name: 'Singed',
        title: 'the Mad Chemist',
        stats: {
            hp: 580,
            mp: 330,
            attackdamage: 63,
            attackspeed: 0.613,
            attackrange: 125,
        },
    },
    {
        key: '14',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sion.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg',
        name: 'Sion',
        title: 'The Undead Juggernaut',
        stats: {
            hp: 545,
            mp: 330,
            attackdamage: 68,
            attackspeed: 0.679,
            attackrange: 175,
        },
    },
    {
        key: '15',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sivir.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sivir_0.jpg',
        name: 'Sivir',
        title: 'the Battle Mistress',
        stats: {
            hp: 562,
            mp: 284,
            attackdamage: 63,
            attackspeed: 0.625,
            attackrange: 500,
        },
    },
    {
        key: '72',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Skarner.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Skarner_0.jpg',
        name: 'Skarner',
        title: 'the Crystal Vanguard',
        stats: {
            hp: 601.28,
            mp: 320,
            attackdamage: 65,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '37',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sona.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_0.jpg',
        name: 'Sona',
        title: 'Maven of the Strings',
        stats: {
            hp: 480,
            mp: 340,
            attackdamage: 49,
            attackspeed: 0.644,
            attackrange: 550,
        },
    },
    {
        key: '16',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Soraka.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_0.jpg',
        name: 'Soraka',
        title: 'the Starchild',
        stats: {
            hp: 535,
            mp: 425,
            attackdamage: 50,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '50',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Swain.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg',
        name: 'Swain',
        title: 'the Noxian Grand General',
        stats: {
            hp: 525,
            mp: 468,
            attackdamage: 58,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '517',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sylas.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg',
        name: 'Sylas',
        title: 'the Unshackled',
        stats: {
            hp: 525,
            mp: 280,
            attackdamage: 61,
            attackspeed: 0.645,
            attackrange: 175,
        },
    },
    {
        key: '134',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Syndra.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Syndra_0.jpg',
        name: 'Syndra',
        title: 'the Dark Sovereign',
        stats: {
            hp: 523,
            mp: 480,
            attackdamage: 53.872,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '223',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/TahmKench.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TahmKench_0.jpg',
        name: 'Tahm Kench',
        title: 'the River King',
        stats: {
            hp: 600,
            mp: 325,
            attackdamage: 56,
            attackspeed: 0.658,
            attackrange: 175,
        },
    },
    {
        key: '163',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Taliyah.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taliyah_0.jpg',
        name: 'Taliyah',
        title: 'the Stoneweaver',
        stats: {
            hp: 532,
            mp: 425,
            attackdamage: 58,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '91',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Talon.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_0.jpg',
        name: 'Talon',
        title: "the Blade's Shadow",
        stats: {
            hp: 588,
            mp: 377.2,
            attackdamage: 68,
            attackspeed: 0.625,
            attackrange: 125,
        },
    },
    {
        key: '44',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Taric.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taric_0.jpg',
        name: 'Taric',
        title: 'the Shield of Valoran',
        stats: {
            hp: 575,
            mp: 300,
            attackdamage: 55,
            attackspeed: 0.625,
            attackrange: 150,
        },
    },
    {
        key: '17',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Teemo.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg',
        name: 'Teemo',
        title: 'the Swift Scout',
        stats: {
            hp: 528,
            mp: 334,
            attackdamage: 54,
            attackspeed: 0.69,
            attackrange: 500,
        },
    },
    {
        key: '412',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Thresh.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg',
        name: 'Thresh',
        title: 'the Chain Warden',
        stats: {
            hp: 560.52,
            mp: 273.92,
            attackdamage: 56,
            attackspeed: 0.625,
            attackrange: 450,
        },
    },
    {
        key: '18',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Tristana.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_0.jpg',
        name: 'Tristana',
        title: 'the Yordle Gunner',
        stats: {
            hp: 559,
            mp: 250,
            attackdamage: 61,
            attackspeed: 0.656,
            attackrange: 525,
        },
    },
    {
        key: '48',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Trundle.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Trundle_0.jpg',
        name: 'Trundle',
        title: 'the Troll King',
        stats: {
            hp: 616,
            mp: 281,
            attackdamage: 68,
            attackspeed: 0.67,
            attackrange: 175,
        },
    },
    {
        key: '23',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Tryndamere.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg',
        name: 'Tryndamere',
        title: 'the Barbarian King',
        stats: {
            hp: 625.64,
            mp: 100,
            attackdamage: 69,
            attackspeed: 0.67,
            attackrange: 125,
        },
    },
    {
        key: '4',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/TwistedFate.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg',
        name: 'Twisted Fate',
        title: 'the Card Master',
        stats: {
            hp: 534,
            mp: 333,
            attackdamage: 52,
            attackspeed: 0.651,
            attackrange: 525,
        },
    },
    {
        key: '29',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Twitch.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Twitch_0.jpg',
        name: 'Twitch',
        title: 'the Plague Rat',
        stats: {
            hp: 612,
            mp: 287.2,
            attackdamage: 59,
            attackspeed: 0.679,
            attackrange: 550,
        },
    },
    {
        key: '77',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Udyr.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_0.jpg',
        name: 'Udyr',
        title: 'the Spirit Walker',
        stats: {
            hp: 594,
            mp: 271,
            attackdamage: 66,
            attackspeed: 0.658,
            attackrange: 125,
        },
    },
    {
        key: '6',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Urgot.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Urgot_0.jpg',
        name: 'Urgot',
        title: 'the Dreadnought',
        stats: {
            hp: 585,
            mp: 340,
            attackdamage: 63,
            attackspeed: 0.625,
            attackrange: 350,
        },
    },
    {
        key: '110',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Varus.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Varus_0.jpg',
        name: 'Varus',
        title: 'the Arrow of Retribution',
        stats: {
            hp: 530,
            mp: 360,
            attackdamage: 61,
            attackspeed: 0.658,
            attackrange: 575,
        },
    },
    {
        key: '67',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vayne.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg',
        name: 'Vayne',
        title: 'the Night Hunter',
        stats: {
            hp: 515,
            mp: 231.8,
            attackdamage: 60,
            attackspeed: 0.658,
            attackrange: 550,
        },
    },
    {
        key: '45',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Veigar.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_0.jpg',
        name: 'Veigar',
        title: 'the Tiny Master of Evil',
        stats: {
            hp: 505,
            mp: 490,
            attackdamage: 52,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '254',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vi.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg',
        name: 'Vi',
        title: 'the Piltover Enforcer',
        stats: {
            hp: 585,
            mp: 295,
            attackdamage: 63,
            attackspeed: 0.644,
            attackrange: 125,
        },
    },
    {
        key: '112',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Viktor.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg',
        name: 'Viktor',
        title: 'the Machine Herald',
        stats: {
            hp: 530,
            mp: 405,
            attackdamage: 53,
            attackspeed: 0.658,
            attackrange: 525,
        },
    },
    {
        key: '8',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vladimir.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vladimir_0.jpg',
        name: 'Vladimir',
        title: 'the Crimson Reaper',
        stats: {
            hp: 537,
            mp: 2,
            attackdamage: 55,
            attackspeed: 0.658,
            attackrange: 450,
        },
    },
    {
        key: '106',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Volibear.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg',
        name: 'Volibear',
        title: 'the Relentless Storm',
        stats: {
            hp: 580,
            mp: 350,
            attackdamage: 60,
            attackspeed: 0.625,
            attackrange: 150,
        },
    },
    {
        key: '19',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Warwick.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg',
        name: 'Warwick',
        title: 'the Uncaged Wrath of Zaun',
        stats: {
            hp: 550,
            mp: 280,
            attackdamage: 65,
            attackspeed: 0.638,
            attackrange: 125,
        },
    },
    {
        key: '498',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Xayah.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xayah_0.jpg',
        name: 'Xayah',
        title: 'the Rebel',
        stats: {
            hp: 590,
            mp: 340,
            attackdamage: 60,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '101',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Xerath.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg',
        name: 'Xerath',
        title: 'the Magus Ascendant',
        stats: {
            hp: 526,
            mp: 459,
            attackdamage: 54.7,
            attackspeed: 0.625,
            attackrange: 525,
        },
    },
    {
        key: '5',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/XinZhao.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg',
        name: 'Xin Zhao',
        title: 'the Seneschal of Demacia',
        stats: {
            hp: 570,
            mp: 273.8,
            attackdamage: 66,
            attackspeed: 0.645,
            attackrange: 175,
        },
    },
    {
        key: '157',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yasuo.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg',
        name: 'Yasuo',
        title: 'the Unforgiven',
        stats: {
            hp: 490,
            mp: 100,
            attackdamage: 60,
            attackspeed: 0.697,
            attackrange: 175,
        },
    },
    {
        key: '777',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yone.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg',
        name: 'Yone',
        title: 'the Unforgotten',
        stats: {
            hp: 550,
            mp: 500,
            attackdamage: 60,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '83',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yorick.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_0.jpg',
        name: 'Yorick',
        title: 'Shepherd of Souls',
        stats: {
            hp: 580,
            mp: 300,
            attackdamage: 62,
            attackspeed: 0.625,
            attackrange: 175,
        },
    },
    {
        key: '350',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yuumi.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg',
        name: 'Yuumi',
        title: 'the Magical Cat',
        stats: {
            hp: 480,
            mp: 400,
            attackdamage: 55,
            attackspeed: 0.625,
            attackrange: 500,
        },
    },
    {
        key: '154',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zac.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zac_0.jpg',
        name: 'Zac',
        title: 'the Secret Weapon',
        stats: {
            hp: 615,
            mp: 0,
            attackdamage: 60,
            attackspeed: 0.736,
            attackrange: 175,
        },
    },
    {
        key: '238',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zed.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg',
        name: 'Zed',
        title: 'the Master of Shadows',
        stats: {
            hp: 584,
            mp: 200,
            attackdamage: 63,
            attackspeed: 0.651,
            attackrange: 125,
        },
    },
    {
        key: '115',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ziggs.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ziggs_0.jpg',
        name: 'Ziggs',
        title: 'the Hexplosives Expert',
        stats: {
            hp: 536,
            mp: 480,
            attackdamage: 54.208,
            attackspeed: 0.656,
            attackrange: 550,
        },
    },
    {
        key: '26',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zilean.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zilean_0.jpg',
        name: 'Zilean',
        title: 'the Chronokeeper',
        stats: {
            hp: 504,
            mp: 452,
            attackdamage: 51.64,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '142',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zoe.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_0.jpg',
        name: 'Zoe',
        title: 'the Aspect of Twilight',
        stats: {
            hp: 560,
            mp: 425,
            attackdamage: 58,
            attackspeed: 0.625,
            attackrange: 550,
        },
    },
    {
        key: '143',
        icon: 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zyra.png',
        img: 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zyra_0.jpg',
        name: 'Zyra',
        title: 'Rise of the Thorns',
        stats: {
            hp: 504,
            mp: 418,
            attackdamage: 53.376,
            attackspeed: 0.625,
            attackrange: 575,
        },
    },
];
